version: '3'

services:
  nexus3:
    # https://blog.sonatype.com/using-nexus-3-as-your-repository-part-3-docker-images
    # https://github.com/samrocketman/nexus3-config-as-code
    image: sonatype/nexus3:latest
    ports:
      - 8081:8081
      - 8082:8082
      - 8083:8083
    volumes:
      - ./nexus-data:/nexus-data
  jenkins:
    image: jenkinsci/blueocean:latest
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_data:/var/jenkins_home
