version: '3'

services:
  docker-registry:
    image: registry:2
    ports:
      - 5000:5000
    restart: always
    volumes:
      - ./volumes:/var/lib/registry
  docker-registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - 8000:80
    environment:
      ENV_DOCKER_REGISTRY_HOST: docker-registry
      ENV_DOCKER_REGISTRY_PORT: 5000
  blueocean:
    image: jenkinsci/blueocean:latest
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_data:/var/jenkins_home:rw
# volumes:
  # jenkins_data:
    # external: true
