version: '3'

services:
  # https://docs.docker.com/registry/configuration/
  nexus3:
    # https://github.com/samrocketman/nexus3-config-as-code
    # https://blog.sonatype.com/using-nexus-3-as-your-repository-part-3-docker-images
    # https://blog.sonatype.com/using-nexus-3-as-your-repository-part-2-npm-packages
    # https://stackoverflow.com/questions/54554490/create-and-use-a-pypi-proxy-repository-on-nexus
    image: sonatype/nexus3:latest
    ports:
      - 8081:8081
      - 8082:8082
      - 8083:8083
    volumes:
      - ./nexus-data:/nexus-data
  jenkins:
    image: jenkinsci/blueocean:latest
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_data:/var/jenkins_home
